# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageDisplay.ui'
#
# Created: Mon Aug 17 15:43:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 637)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.seriesLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seriesLabel.sizePolicy().hasHeightForWidth())
        self.seriesLabel.setSizePolicy(sizePolicy)
        self.seriesLabel.setAutoFillBackground(False)
        self.seriesLabel.setStyleSheet("background-color : white")
        self.seriesLabel.setText("")
        self.seriesLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.seriesLabel.setObjectName("seriesLabel")
        self.verticalLayout_5.addWidget(self.seriesLabel)
        self.fileNameLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLabel.sizePolicy().hasHeightForWidth())
        self.fileNameLabel.setSizePolicy(sizePolicy)
        self.fileNameLabel.setStyleSheet("background-color : white")
        self.fileNameLabel.setText("")
        self.fileNameLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.verticalLayout_5.addWidget(self.fileNameLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinTime = QtGui.QSpinBox(self.centralwidget)
        self.spinTime.setMinimum(1)
        self.spinTime.setObjectName("spinTime")
        self.verticalLayout_2.addWidget(self.spinTime)
        self.spinSlice = QtGui.QSpinBox(self.centralwidget)
        self.spinSlice.setMinimum(1)
        self.spinSlice.setMaximum(100)
        self.spinSlice.setObjectName("spinSlice")
        self.verticalLayout_2.addWidget(self.spinSlice)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sliderTime = QtGui.QSlider(self.centralwidget)
        self.sliderTime.setMinimum(1)
        self.sliderTime.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTime.setObjectName("sliderTime")
        self.verticalLayout_3.addWidget(self.sliderTime)
        self.sliderSlice = QtGui.QSlider(self.centralwidget)
        self.sliderSlice.setMinimum(1)
        self.sliderSlice.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSlice.setObjectName("sliderSlice")
        self.verticalLayout_3.addWidget(self.sliderSlice)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pixelVal = QtGui.QLabel(self.centralwidget)
        self.pixelVal.setObjectName("pixelVal")
        self.horizontalLayout_3.addWidget(self.pixelVal)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.roiFreehand = QtGui.QToolButton(self.centralwidget)
        self.roiFreehand.setCheckable(True)
        self.roiFreehand.setObjectName("roiFreehand")
        self.horizontalLayout_3.addWidget(self.roiFreehand)
        self.roiButton = QtGui.QToolButton(self.centralwidget)
        self.roiButton.setCheckable(True)
        self.roiButton.setObjectName("roiButton")
        self.horizontalLayout_3.addWidget(self.roiButton)
        self.roiClearSlice = QtGui.QToolButton(self.centralwidget)
        self.roiClearSlice.setObjectName("roiClearSlice")
        self.horizontalLayout_3.addWidget(self.roiClearSlice)
        self.roiClear = QtGui.QToolButton(self.centralwidget)
        self.roiClear.setObjectName("roiClear")
        self.horizontalLayout_3.addWidget(self.roiClear)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 493, 450))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = ImageSliceDisplayLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setMargin(0)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 21))
        self.menubar.setObjectName("menubar")
        self.menuImage = QtGui.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuROI = QtGui.QMenu(self.menubar)
        self.menuROI.setObjectName("menuROI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionMaximum_Intensity_Map = QtGui.QAction(MainWindow)
        self.actionMaximum_Intensity_Map.setObjectName("actionMaximum_Intensity_Map")
        self.actionMean_baseline_image = QtGui.QAction(MainWindow)
        self.actionMean_baseline_image.setObjectName("actionMean_baseline_image")
        self.actionAorta_Seed_Voxel = QtGui.QAction(MainWindow)
        self.actionAorta_Seed_Voxel.setObjectName("actionAorta_Seed_Voxel")
        self.actionFloodfill_from_seed = QtGui.QAction(MainWindow)
        self.actionFloodfill_from_seed.setObjectName("actionFloodfill_from_seed")
        self.actionSelect_AIF_voxels = QtGui.QAction(MainWindow)
        self.actionSelect_AIF_voxels.setObjectName("actionSelect_AIF_voxels")
        self.menuImage.addAction(self.actionOpen)
        self.menuAnalysis.addAction(self.actionMaximum_Intensity_Map)
        self.menuAnalysis.addAction(self.actionMean_baseline_image)
        self.menuROI.addAction(self.actionSelect_AIF_voxels)
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuROI.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.spinSlice, QtCore.SIGNAL("valueChanged(int)"), self.sliderSlice.setValue)
        QtCore.QObject.connect(self.sliderSlice, QtCore.SIGNAL("valueChanged(int)"), self.spinSlice.setValue)
        QtCore.QObject.connect(self.spinTime, QtCore.SIGNAL("valueChanged(int)"), self.sliderTime.setValue)
        QtCore.QObject.connect(self.sliderTime, QtCore.SIGNAL("valueChanged(int)"), self.spinTime.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Time Series Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Series name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "time point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "slice", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelVal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.roiFreehand.setText(QtGui.QApplication.translate("MainWindow", "Draw freehand", None, QtGui.QApplication.UnicodeUTF8))
        self.roiButton.setText(QtGui.QApplication.translate("MainWindow", "Draw ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.roiClearSlice.setText(QtGui.QApplication.translate("MainWindow", "Clear Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.roiClear.setText(QtGui.QApplication.translate("MainWindow", "Clear ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImage.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnalysis.setTitle(QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuROI.setTitle(QtGui.QApplication.translate("MainWindow", "AIF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaximum_Intensity_Map.setText(QtGui.QApplication.translate("MainWindow", "Maximum Intensity Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMean_baseline_image.setText(QtGui.QApplication.translate("MainWindow", "Mean baseline image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAorta_Seed_Voxel.setText(QtGui.QApplication.translate("MainWindow", "Aorta Seed Voxel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFloodfill_from_seed.setText(QtGui.QApplication.translate("MainWindow", "Floodfill from seed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_AIF_voxels.setText(QtGui.QApplication.translate("MainWindow", "Select AIF voxels", None, QtGui.QApplication.UnicodeUTF8))

from ImageDisplayWindow.ImageSliceDisplayLabel import ImageSliceDisplayLabel
