# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NumberInput.ui'
#
# Created: Thu Aug 27 12:48:20 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NumberInput(object):
    def setupUi(self, NumberInput):
        NumberInput.setObjectName("NumberInput")
        NumberInput.resize(391, 199)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NumberInput.sizePolicy().hasHeightForWidth())
        NumberInput.setSizePolicy(sizePolicy)
        self.layoutWidget = QtGui.QWidget(NumberInput)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 367, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_description = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_description.setText("")
        self.label_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.gridLayout.addWidget(self.label_description, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_slice = QtGui.QLabel(self.layoutWidget)
        self.label_slice.setObjectName("label_slice")
        self.verticalLayout.addWidget(self.label_slice)
        self.label_xKernel = QtGui.QLabel(self.layoutWidget)
        self.label_xKernel.setObjectName("label_xKernel")
        self.verticalLayout.addWidget(self.label_xKernel)
        self.label_yKernel = QtGui.QLabel(self.layoutWidget)
        self.label_yKernel.setObjectName("label_yKernel")
        self.verticalLayout.addWidget(self.label_yKernel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinBox_slice = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_slice.setMinimum(1)
        self.spinBox_slice.setObjectName("spinBox_slice")
        self.verticalLayout_2.addWidget(self.spinBox_slice)
        self.spinBox_xKernel = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_xKernel.setMinimum(1)
        self.spinBox_xKernel.setSingleStep(2)
        self.spinBox_xKernel.setObjectName("spinBox_xKernel")
        self.verticalLayout_2.addWidget(self.spinBox_xKernel)
        self.spinBox_yKernel = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_yKernel.setMinimum(1)
        self.spinBox_yKernel.setSingleStep(2)
        self.spinBox_yKernel.setProperty("value", 5)
        self.spinBox_yKernel.setObjectName("spinBox_yKernel")
        self.verticalLayout_2.addWidget(self.spinBox_yKernel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.slider_slice = QtGui.QSlider(self.layoutWidget)
        self.slider_slice.setMinimum(1)
        self.slider_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slice.setObjectName("slider_slice")
        self.verticalLayout_3.addWidget(self.slider_slice)
        self.slider_xKernel = QtGui.QSlider(self.layoutWidget)
        self.slider_xKernel.setMinimum(1)
        self.slider_xKernel.setSingleStep(2)
        self.slider_xKernel.setOrientation(QtCore.Qt.Horizontal)
        self.slider_xKernel.setObjectName("slider_xKernel")
        self.verticalLayout_3.addWidget(self.slider_xKernel)
        self.slider_yKernel = QtGui.QSlider(self.layoutWidget)
        self.slider_yKernel.setMinimum(1)
        self.slider_yKernel.setSingleStep(2)
        self.slider_yKernel.setProperty("value", 5)
        self.slider_yKernel.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yKernel.setObjectName("slider_yKernel")
        self.verticalLayout_3.addWidget(self.slider_yKernel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(NumberInput)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NumberInput.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NumberInput.reject)
        QtCore.QObject.connect(self.spinBox_slice, QtCore.SIGNAL("valueChanged(int)"), self.slider_slice.setValue)
        QtCore.QObject.connect(self.slider_slice, QtCore.SIGNAL("sliderMoved(int)"), self.spinBox_slice.setValue)
        QtCore.QObject.connect(self.slider_xKernel, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_xKernel.setValue)
        QtCore.QObject.connect(self.spinBox_xKernel, QtCore.SIGNAL("valueChanged(int)"), self.slider_xKernel.setValue)
        QtCore.QObject.connect(self.slider_yKernel, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_yKernel.setValue)
        QtCore.QObject.connect(self.spinBox_yKernel, QtCore.SIGNAL("valueChanged(int)"), self.slider_yKernel.setValue)
        QtCore.QMetaObject.connectSlotsByName(NumberInput)

    def retranslateUi(self, NumberInput):
        NumberInput.setWindowTitle(QtGui.QApplication.translate("NumberInput", "Number of candidate voxels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_slice.setText(QtGui.QApplication.translate("NumberInput", "Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xKernel.setText(QtGui.QApplication.translate("NumberInput", "Kernel: x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_yKernel.setText(QtGui.QApplication.translate("NumberInput", "Kernel: y", None, QtGui.QApplication.UnicodeUTF8))

